name: Preacher
description: An app to read your spiritual books.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  splashscreen: ^1.3.4
  auto_size_text: ^2.1.0
  json_annotation: ^2.4.0
  json_table: ^1.4.0
  dio: ^3.0.10
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
     - lib/img/
